### PR TITLE
Install the libgbm-dev package

### PR DESCRIPTION
**Pull request by papandreou**
It's a new requirement of puppeteer 3: https://github.com/puppeteer/puppeteer/issues/5661

### CODE REVIEW

**Review by vgrigoruk — APPROVED** [review]

**Comment by papandreou** [comment]
@vgrigoruk, thanks a lot for the late night review 🌔 ⌨️

I don't have write access to this repository, so I can't merge it. Could you help with that?

**Comment by vgrigoruk** [comment]
it seems like I don't have write access as well :)
btw, there is a commit in the upstream repo that doesn't the same (but adds another package): https://github.com/jontewks/puppeteer-heroku-buildpack/commit/939d212be14e06b90bed7b8dcb608da5c918eb31

**Comment by papandreou** [comment]
Hmm, right, it's probably better to go with that, then. That commit seems to be the only difference between our fork's `master` and the upstream: https://github.com/jontewks/puppeteer-heroku-buildpack/compare/jontewks:master..peakon:master

I wonder why we created the fork in the first place? For security reasons, so we wouldn't automatically pick up new, potentially evil stuff from upstream?

@deppy, can you help grant write access here (or get the upstream's master merged in)?

**Comment by deppy** [comment]
@papandreou Did both granted access [here](https://github.com/peakon/infrastructure/pull/312) and then merged upstream's master:
```
Updating 7998008..939d212
Fast-forward
 bin/compile | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by deppy** [comment]
And yeah, we forked all the buildpacks (that are non-official / non-heroku buildpacks) so that we wouldn't introduce possible places for unauthorized executables being introduced.

**Comment by papandreou** [comment]
Thanks both!

> And yeah, we forked all the buildpacks (that are non-official / non-heroku buildpacks) so that we wouldn't introduce possible places for unauthorized executables being introduced.

Okay, makes sense. At least we now that for next time now :)

**Pull request closed without merging**
